image: docker:19.03.8

stages:
 - build
 - deploy
 
build:
  stage: build
  services:
  - docker:19.03.8-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest

deploy:
  type: deploy
  image: alpine
  environment: production
  script:
    - apk update
    - apk add --update --no-cache openssh sshpass
    - mkdir api
    - chmod +x api
    - cp docker-compose.yml api
    - sshpass -p ${SERVER_PASSWORD} scp -o stricthostkeychecking=no -r api ${SERVER_USERNAME}@${SERVER_IP}:/
    - sshpass -p ${SERVER_PASSWORD} ssh -o StrictHostKeyChecking=no ${SERVER_USERNAME}@${SERVER_IP} "cd /api; docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}; docker-compose down; docker image rm ${CI_REGISTRY_IMAGE}; docker-compose up -d;"
  only:
    - master
